name: PW | Run Jest

on: push

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: '22.13.1'
                  cache: 'npm'
                  cache-dependency-path: ./package-lock.json

            - name: Install Node Packages
              run: pnpm install --frozen-lockfile
              working-directory: ./

            - name: Run Tests
              run: pnpm test
              working-directory: ./
